### ISSUE TITLE
Crash when shooting withing enemy

### ISSUE THREAD

**Issue by p-98** [uni-tj/robo-arena#119]
Shooting within an enemy produces the following error:

```
Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/timon/Documents/uni/robo-arena/src/roboarena/index.py", line 44, in <lambda>
    server_thread = Thread(target=lambda: server.loop())
                                          ^^^^^^^^^^^^^
  File "/Users/timon/Documents/uni/robo-arena/src/roboarena/server/server.py", line 335, in loop
    GameState(self, clients).loop()
  File "/Users/timon/Documents/uni/robo-arena/src/roboarena/server/server.py", line 292, in loop
    entity.tick(dt_frame, t_frame)
  File "/Users/timon/Documents/uni/robo-arena/src/roboarena/server/entity.py", line 235, in tick
    if entity not in self._hit_last_tick:
                     ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ServerPlayerBullet' object has no attribute '_hit_last_tick'
```

**Comment by JulesOxe** [comment]
Resolved by #136
